spring:
  application:
    name: spring-cloud-demo-consumer
#  cloud:
#    config:
#      discovery:
#        service-id: spring-cloud-demo-config
#        enabled: true
#      profile: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  #      defaultZone: http://39.98.245.101:9000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 7300

feign:
  hystrix:
    enabled: true