server:
  port: 9100

#配置注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
#    metadata-map:
#      user:
#        name: zhanglong
#        password: zl123456

    #    192.168.0.104
    #${eureka.instance.ip-address} 决定服务跳转host，必须指定
    #ip-address: 192.168.1.1 #强制指定IP地址，默认会获取本机的IP地址 决定Eureka服务显示host
    ip-address: 118.25.55.79
  #    以IP地址注册到服务中心 生产环境要注释掉
  #    prefer-ip-address: true #不设可自己指定，true会自动获取本地ipv4地址
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
spring:
  application:
    name: @project.artifactId@

