xxl:
  job:
    admin:
      addresses: http://192.168.1.212:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: 192.168.1.212
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
    accessToken:

